### PR TITLE
Use xlsx mini

### PR DESCRIPTION
**Pull request by elyse0**
Using 'xlsx.mini.min' decreases the stat size to 222kb 😄 

image

### CODE REVIEW

**Comment by LuisEnMarroquin** [comment]
It's not letting me do the merge 😥

image

Can you merge my `develop` into your `mini-xlsx-2` to solve the conflict?

The problem is only this line

image

**Comment by LuisEnMarroquin** [comment]
Web editor is not letting me do merge and then fix conflicts, not very well thought out from GitHub 🤔

image

**Comment by elyse0** [comment]
> It's not letting me do the merge disappointed_relieved
> 
> image
> 
> Can you merge my `develop` into your `mini-xlsx-2` to solve the conflict?
> 
> The problem is only this line
> 
> image

That's the line I modified 😆

**Comment by elyse0** [comment]
Did you try this?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Comment by elyse0** [comment]
It was my bad 😞  but I've fixed it

**Comment by LuisEnMarroquin** [comment]
Merged and published `2.3.0` thanks 🤗

**Pull request merged**
